<?php

declare(strict_types=1);

namespace App\Model;

use Hyperf\DbConnection\Model\Model;

class Layout extends Model
{
    protected ?string $table = 'layouts';

    protected string $keyType = 'string';

    public bool $incrementing = false;

    protected array $fillable = [
        'code',
        'name',
        'format',
        'sector',
        'movement_type',
        'start_row',
        'num_doc_column',
        'parcel_separator',
        'date_column',
        'history_column',
        'history_2_lines_column',
        'debit_value_column',
        'credit_value_column',
        'interest_column',
        'fine_column',
        'discounts_column',
        'refund_values_column',
        'other_values_column',
        'ignore_history',
        'client_supplier_column',
        'cpf_cnpj_column',
        'debit_credit_column',
        'due_date_column',
        'bank_column',
        'third_party_participant_column',
        'additional_information_column',
        'complement_column',
        'debit_account_column',
        'credit_account_column',
        'filial_column',
        'additional_information_2_column',
        'additional_information_3_column',
        'consider_previous_date',
        'consider_previous_client_supplier',
        'consider_previous_adicional_information',
        'consider_previous_history',
        'consider_previous_filial',
        'consider_previous_bank',
        'consider_history_only_fline',
        'is_default_layout',
        'has_d_c_account',
        'copy_third_party_participant_doc',
        'request_month',
        'request_year',
        'request_serie',
        'request_especie',
        'contract_id',
        'consider_dc_for_accounting_rules',
        'consider_history_for_accounting_rules',
        'consider_participant_doc_for_accounting_rules',
        'consider_participant_for_accounting_rules',
        'consider_bank_for_accounting_rules',
        'consider_filial_for_accounting_rules',
        'consider_additional_info_for_accounting_rules',
        'consider_additional_info_2_for_accounting_rules',
        'consider_additional_info_3_for_accounting_rules',
        'consider_rule_extra_for_accounting_rules',
        'include_document_number_in_history_when_export',
        'remove_line_break_in_history_when_export',
        'keep_original_values_when_import',
        'show_document_number',
        'show_parcel',
        'hide_in_list',
        'show_participant',
        'show_bank',
        'enable_edit_in_grid',
        'show_filial',
        'show_complement',
        'show_additional_info_1',
        'show_additional_info_2',
        'show_additional_info_3',
        'change_document_number',
        'invert_sign',
        'import_blocked_entries',
        'bank_statement',
        'bring_1_as_default_parcel',
        'confront_consider_banks',
        'personalized_field_date',
        'personalized_field_value',
        'personalized_field_document',
        'personalized_field_history',
        'reference_layout',
        'parcel_separator_when_import',
        'day_to_add_when_import',
        'comments',
        'layouts_admin_id',
        'tariff_column',
        'addition_column',
        'request_password',
        'request_input',
        'request_input_title',
        'participant_marking_enabled',
        'is_layout_master',
        'pis_column',
        'cofins_column',
        'csll_column',
        'irrf_column',
        'pis_cosirf_column',
        'cofins_cosirf_column',
        'csll_cosirf_column',
        'irpj_cosirf_column',
        'irrfp_column',
    ];
}
